name: Deploy Hugo

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Важно: Linux, не Windows!
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo 0.145.0 Extended (Linux)
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz
          tar -xzf hugo_extended_*.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version  # Проверка установки

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true